# Generated by Django 6.0.3 on 2026-03-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_city_user_district_user_street_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='residential_status',
            field=models.CharField(choices=[('OWNER', 'მესაკუთრე'), ('TENANT', 'არა მესაკუთრე')], default='OWNER', max_length=20),
        ),
    ]
