# Generated by Django 6.0.3 on 2026-03-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='polls/documents/'),
        ),
        migrations.AddField(
            model_name='poll',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='polls/images/'),
        ),
        migrations.AddField(
            model_name='poll',
            name='passing_percentage',
            field=models.PositiveIntegerField(default=50, help_text='მინიმალური მომხრეების პროცენტი (მაგ. 50 ან 60)'),
        ),
    ]
