# Generated by Django 6.0.3 on 2026-03-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_poll_document_poll_image_poll_passing_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='owners_only',
            field=models.BooleanField(default=False, verbose_name='მხოლოდ მფლობელები'),
        ),
    ]
