# Generated by Django 6.0.3 on 2026-03-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_poll_owners_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='budget',
            field=models.PositiveIntegerField(default=0, verbose_name='საჭირო ბიუჯეტი'),
        ),
    ]
