# Generated by Django 6.0.3 on 2026-03-09 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='სათაური')),
                ('file', models.FileField(upload_to='documents/', verbose_name='ფაილი')),
                ('category', models.CharField(choices=[('general', 'საერთო'), ('financial', 'ფინანსური'), ('rules', 'წესდება'), ('protocols', 'ოქმები')], default='general', max_length=20, verbose_name='კატეგორია')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
