# Generated by Django 6.0.3 on 2026-03-09 14:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-recorded_date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='აღწერა'),
        ),
        migrations.AddField(
            model_name='document',
            name='recorded_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='თარიღი'),
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/', verbose_name='ფაილი')),
                ('original_name', models.CharField(max_length=255, verbose_name='ფაილის სახელი')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='documents.document')),
            ],
        ),
    ]
