# Generated by Django 6.0.3 on 2026-03-07 12:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorPass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pass_type', models.CharField(choices=[('guest', 'სტუმარი'), ('courier', 'კურიერი'), ('service', 'სერვისი')], max_length=20)),
                ('visitor_name', models.CharField(max_length=255)),
                ('car_plate', models.CharField(blank=True, max_length=20)),
                ('scheduled_datetime', models.DateTimeField()),
                ('notify_on_arrival', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'მოლოდინში'), ('entered', 'შემოვიდა'), ('completed', 'დასრულებული'), ('cancelled', 'გაუქმებული')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_datetime'],
            },
        ),
    ]
