# Generated by Django 6.0.3 on 2026-03-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitorpass',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='visitorpass',
            name='scheduled_datetime',
        ),
        migrations.AddField(
            model_name='visitorpass',
            name='duration_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
