# Generated by Django 6.0.3 on 2026-03-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0002_alter_visitorpass_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorpass',
            name='pass_type',
            field=models.CharField(choices=[('guest', 'სტუმარი'), ('courier', 'კურიერი'), ('taxi', 'ტაქსი'), ('service', 'სერვისი')], max_length=20),
        ),
    ]
